name: build

on:
  pull_request:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3.6.0
    - uses: actions/setup-node@v3.2.0
      with:
         node-version: '14.x'
    - name: use node
      run: |
       npm install
       npm run build